from enum import Enum

class KafkaErrorCode(Enum):
    NO_ERROR = 0                    # No error
    OFFSET_OUT_OF_RANGE = 1          # Offset out of range
    CORRUPT_MESSAGE = 2              # Message is corrupt
    UNKNOWN_TOPIC_OR_PARTITION = 3   # Unknown topic or partition
    INVALID_FETCH_SIZE = 4           # Invalid fetch size
    LEADER_NOT_AVAILABLE = 5         # Leader not available
    NOT_LEADER_OR_FOLLOWER = 6       # Not leader for partition
    REQUEST_TIMED_OUT = 7            # Request timed out
    BROKER_NOT_AVAILABLE = 8         # Broker not available
    REPLICA_NOT_AVAILABLE = 9        # Replica not available
    MESSAGE_TOO_LARGE = 10           # Message size exceeds limit
    STALE_CONTROLLER_EPOCH = 11      # Stale controller epoch
    OFFSET_METADATA_TOO_LARGE = 12   # Offset metadata is too large
    NETWORK_EXCEPTION = 13           # Network exception
    COORDINATOR_LOAD_IN_PROGRESS = 14 # Coordinator load in progress
    COORDINATOR_NOT_AVAILABLE = 15   # Coordinator not available
    NOT_COORDINATOR = 16             # Not coordinator for group
    INVALID_TOPIC_EXCEPTION = 17     # Invalid topic
    RECORD_LIST_TOO_LARGE = 18       # Record list too large
    NOT_ENOUGH_REPLICAS = 19         # Not enough replicas
    NOT_ENOUGH_REPLICAS_AFTER_APPEND = 20 # Not enough replicas after append
    INVALID_REQUIRED_ACKS = 21       # Invalid required acks
    ILLEGAL_GENERATION = 22          # Illegal generation
    INCONSISTENT_GROUP_PROTOCOL = 23 # Inconsistent group protocol
    INVALID_GROUP_ID = 24            # Invalid group ID
    UNKNOWN_MEMBER_ID = 25           # Unknown member ID
    INVALID_SESSION_TIMEOUT = 26     # Invalid session timeout
    REBALANCE_IN_PROGRESS = 27       # Rebalance in progress
    INVALID_COMMIT_OFFSET_SIZE = 28  # Invalid commit offset size
    TOPIC_AUTHORIZATION_FAILED = 29  # Topic authorization failed
    GROUP_AUTHORIZATION_FAILED = 30  # Group authorization failed
    CLUSTER_AUTHORIZATION_FAILED = 31 # Cluster authorization failed
    INVALID_TIMESTAMP = 32           # Invalid timestamp
    UNSUPPORTED_SASL_MECHANISM = 33  # Unsupported SASL mechanism
    ILLEGAL_SASL_STATE = 34          # Illegal SASL state
    UNSUPPORTED_VERSION = 35         # Unsupported version
    TOPIC_ALREADY_EXISTS = 36        # Topic already exists
    INVALID_PARTITIONS = 37          # Invalid number of partitions
    INVALID_REPLICATION_FACTOR = 38  # Invalid replication factor
    INVALID_REPLICA_ASSIGNMENT = 39  # Invalid replica assignment
    INVALID_CONFIG = 40              # Invalid configuration
    NOT_CONTROLLER = 41              # Not controller
    INVALID_REQUEST = 42             # Invalid request
    UNSUPPORTED_FOR_MESSAGE_FORMAT = 43 # Unsupported message format
    POLICY_VIOLATION = 44            # Policy violation
    OUT_OF_ORDER_SEQUENCE_NUMBER = 45 # Out of order sequence number
    DUPLICATE_SEQUENCE_NUMBER = 46   # Duplicate sequence number
    INVALID_PRODUCER_EPOCH = 47      # Invalid producer epoch
    INVALID_TXN_STATE = 48           # Invalid transaction state
    INVALID_PRODUCER_ID_MAPPING = 49 # Invalid producer ID mapping
    INVALID_TRANSACTION_TIMEOUT = 50 # Invalid transaction timeout
    CONCURRENT_TRANSACTIONS = 51     # Concurrent transactions
    TRANSACTION_COORDINATOR_FENCED = 52 # Transaction coordinator fenced
    TRANSACTIONAL_ID_AUTHORIZATION_FAILED = 53 # Transactional ID authorization failed
    SECURITY_DISABLED = 54           # Security features are disabled
    OPERATION_NOT_ATTEMPTED = 55     # Operation not attempted
    KAFKA_STORAGE_ERROR = 56         # Kafka storage error
    LOG_DIR_NOT_FOUND = 57           # Log directory not found
    SASL_AUTHENTICATION_FAILED = 58  # SASL authentication failed
    UNKNOWN_PRODUCER_ID = 59         # Unknown producer ID
    REASSIGNMENT_IN_PROGRESS = 60    # Reassignment in progress
    DELEGATION_TOKEN_AUTH_DISABLED = 61 # Delegation token feature disabled
    DELEGATION_TOKEN_NOT_FOUND = 62  # Delegation token not found
    DELEGATION_TOKEN_OWNER_MISMATCH = 63 # Delegation token owner mismatch
    DELEGATION_TOKEN_REQUEST_NOT_ALLOWED = 64 # Delegation token request not allowed
    DELEGATION_TOKEN_AUTHORIZATION_FAILED = 65 # Delegation token authorization failed
    DELEGATION_TOKEN_EXPIRED = 66    # Delegation token expired
    INVALID_PRINCIPAL_TYPE = 67      # Invalid principal type
    NON_EMPTY_GROUP = 68             # Group is not empty
    GROUP_ID_NOT_FOUND = 69          # Group ID not found
    FETCH_SESSION_ID_NOT_FOUND = 70  # Fetch session ID not found
    INVALID_FETCH_SESSION_EPOCH = 71 # Invalid fetch session epoch
    LISTENER_NOT_FOUND = 72          # Listener not found
    TOPIC_DELETION_DISABLED = 73     # Topic deletion disabled
    FENCED_LEADER_EPOCH = 74         # Fenced leader epoch
    UNKNOWN_LEADER_EPOCH = 75        # Unknown leader epoch
    UNSUPPORTED_COMPRESSION_TYPE = 76 # Unsupported compression type
    STALE_BROKER_EPOCH = 77          # Stale broker epoch
    OFFSET_NOT_AVAILABLE = 78        # Offset not available
    MEMBER_ID_REQUIRED = 79          # Member ID required
    PREFERRED_LEADER_NOT_AVAILABLE = 80 # Preferred leader not available
    GROUP_MAX_SIZE_REACHED = 81      # Group max size reached
    FENCED_INSTANCE_ID = 82          # Fenced instance ID
    ELIGIBLE_LEADERS_NOT_AVAILABLE = 83 # No eligible leaders
    ELECTION_NOT_NEEDED = 84         # Election not needed
    NO_REASSIGNMENT_IN_PROGRESS = 85 # No reassignment in progress
    GROUP_SUBSCRIBED_TO_TOPIC = 86   # Group subscribed to a topic
    INVALID_RECORD = 87                     # Invalid record
    UNSTABLE_OFFSET_COMMIT = 88             # Unstable offset commit
    THROTTLING_QUOTA_EXCEEDED = 89          # Throttling quota exceeded
    PRODUCER_FENCED = 90                    # Producer fenced by another producer
    RESOURCE_NOT_FOUND = 91                 # Requested resource not found
    DUPLICATE_RESOURCE = 92                 # Duplicate resource creation
    UNACCEPTABLE_CREDENTIAL = 93            # Unacceptable credential used
    INCONSISTENT_VOTER_SET = 94             # Inconsistent voter set in quorum
    INVALID_UPDATE_VERSION = 95             # Invalid update version
    FEATURE_UPDATE_FAILED = 96              # Failed to update broker feature
    PRINCIPAL_DESERIALIZATION_FAILURE = 97  # Failed to deserialize principal
    SNAPSHOT_NOT_FOUND = 98                      # Requested snapshot was not found.
    POSITION_OUT_OF_RANGE = 99                   # Requested position is not greater than or equal to zero, and less than the size of the snapshot.
    UNKNOWN_TOPIC_ID = 100                       # This server does not host this topic ID.
    DUPLICATE_BROKER_REGISTRATION = 101          # This broker ID is already in use.
    BROKER_ID_NOT_REGISTERED = 102               # The given broker ID was not registered.
    INCONSISTENT_TOPIC_ID = 103                  # The log's topic ID did not match the topic ID in the request.
    INCONSISTENT_CLUSTER_ID = 104                 # The clusterId in the request does not match that found on the server.
    TRANSACTIONAL_ID_NOT_FOUND = 105              # The transactionalId could not be found.
    FETCH_SESSION_TOPIC_ID_ERROR = 106            # The fetch session encountered inconsistent topic ID usage.
    INELIGIBLE_REPLICA = 107                      # The new ISR contains at least one ineligible replica.
    NEW_LEADER_ELECTED = 108                      # The AlterPartition request successfully updated the partition state but the leader has changed.
    OFFSET_MOVED_TO_TIERED_STORAGE = 109          # The requested offset is moved to tiered storage.
    FENCED_MEMBER_EPOCH = 110                     # The member epoch is fenced by the group coordinator.
    UNRELEASED_INSTANCE_ID = 111                  # The instance ID is still used by another member in the consumer group.
    UNSUPPORTED_ASSIGNOR = 112                     # The assignor or its version range is not supported by the consumer group.
    STALE_MEMBER_EPOCH = 113                      # The member epoch is stale. 
    MISMATCHED_ENDPOINT_TYPE = 114                # The request was sent to an endpoint of the wrong type.
    UNSUPPORTED_ENDPOINT_TYPE = 115               # This endpoint type is not supported yet.
    UNKNOWN_CONTROLLER_ID = 116                   # This controller ID is not known.
    UNKNOWN_SUBSCRIPTION_ID = 117                  # Invalid or outdated subscription ID.
    TELEMETRY_TOO_LARGE = 118                     # Push telemetry request larger than the maximum size the broker will accept.
    INVALID_REGISTRATION = 119                    # The broker registration is considered to be invalid.
    TRANSACTION_ABORTABLE = 120                    # The server encountered an error with the transaction.
